name: CI Testing

on: [push]

jobs:
  build:
    env:
      TRANSLATION_CREDS: ${{ secrets.TRANSLATION_CREDS }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14.18.1']
        mongodb-version: ['5.0.3']

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start
